model:
  name: "gpt-4"
  disentangled: true
  classmode: 'pred'
  incontext: 0
  gridsearch: false
  nreturn: 7
  temperature: 0.5
  sampling: true
  api_key: ""
  or_key: ""
  prompt: "Complete the Raven's progressive matrix:"
  prefix: "Only return the missing numbers!\n"
